# coding: utf-8

"""
    First Approach to an GUARD API

    We'll be here writing some things in order to make it work with data  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConfigurationProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'value': 'list[ConfigurationPropertiesValue]',
        'metadata': 'Metadata'
    }

    attribute_map = {
        'type': 'type',
        'value': 'value',
        'metadata': 'metadata'
    }

    def __init__(self, type=None, value=None, metadata=None):  # noqa: E501
        """ConfigurationProperties - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._value = None
        self._metadata = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if value is not None:
            self.value = value
        if metadata is not None:
            self.metadata = metadata

    @property
    def type(self):
        """Gets the type of this ConfigurationProperties.  # noqa: E501


        :return: The type of this ConfigurationProperties.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ConfigurationProperties.


        :param type: The type of this ConfigurationProperties.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def value(self):
        """Gets the value of this ConfigurationProperties.  # noqa: E501


        :return: The value of this ConfigurationProperties.  # noqa: E501
        :rtype: list[ConfigurationPropertiesValue]
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ConfigurationProperties.


        :param value: The value of this ConfigurationProperties.  # noqa: E501
        :type: list[ConfigurationPropertiesValue]
        """

        self._value = value

    @property
    def metadata(self):
        """Gets the metadata of this ConfigurationProperties.  # noqa: E501


        :return: The metadata of this ConfigurationProperties.  # noqa: E501
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this ConfigurationProperties.


        :param metadata: The metadata of this ConfigurationProperties.  # noqa: E501
        :type: Metadata
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if value is None:
                break
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigurationProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigurationProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
