# coding: utf-8

"""
    First Approach to an GUARD API

    We'll be here writing some things in order to make it work with data  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.security_properties_value import SecurityPropertiesValue  # noqa: E501
from swagger_client.rest import ApiException


class TestSecurityPropertiesValue(unittest.TestCase):
    """SecurityPropertiesValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecurityPropertiesValue(self):
        """Test SecurityPropertiesValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.security_properties_value.SecurityPropertiesValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
