# coding: utf-8

"""
    First Approach to an GUARD API

    We'll be here writing some things in order to make it work with data  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.configurations_properties_value import ConfigurationsPropertiesValue  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigurationsPropertiesValue(unittest.TestCase):
    """ConfigurationsPropertiesValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigurationsPropertiesValue(self):
        """Test ConfigurationsPropertiesValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.configurations_properties_value.ConfigurationsPropertiesValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
