# coding: utf-8

"""
    First Approach to an GUARD API

    We'll be here writing some things in order to make it work with data  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_agents_get(self):
        """Test case for agents_get

        Gets the information of an Agent  # noqa: E501
        """
        pass

    def test_agents_id_delete(self):
        """Test case for agents_id_delete

        Deletes (unregisters) the Agent from the CB  # noqa: E501
        """
        pass

    def test_agents_id_get(self):
        """Test case for agents_id_get

        Gets the properties of an agent.  # noqa: E501
        """
        pass

    def test_agents_ping_id_put(self):
        """Test case for agents_ping_id_put

        Puts a ping to GUARD Agent  # noqa: E501
        """
        pass

    def test_agents_register_post(self):
        """Test case for agents_register_post

        Post a new GUARD Agent  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
