# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util
import re

class ConfigurationPropertiesValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, type: str=None, description: str=None, value: str=None):  # noqa: E501
        """ConfigurationPropertiesValue - a model defined in Swagger

        :param name: The name of this ConfigurationPropertiesValue.  # noqa: E501
        :type name: str
        :param type: The type of this ConfigurationPropertiesValue.  # noqa: E501
        :type type: str
        :param description: The description of this ConfigurationPropertiesValue.  # noqa: E501
        :type description: str
        :param value: The value of this ConfigurationPropertiesValue.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'name': str,
            'type': str,
            'description': str,
            'value': str
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type',
            'description': 'description',
            'value': 'value'
        }

        self._name = name
        self._type = type
        self._description = description
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigurationPropertiesValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The configuration_properties_value of this ConfigurationPropertiesValue.  # noqa: E501
        :rtype: ConfigurationPropertiesValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ConfigurationPropertiesValue.


        :return: The name of this ConfigurationPropertiesValue.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ConfigurationPropertiesValue.


        :param name: The name of this ConfigurationPropertiesValue.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this ConfigurationPropertiesValue.


        :return: The type of this ConfigurationPropertiesValue.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ConfigurationPropertiesValue.


        :param type: The type of this ConfigurationPropertiesValue.
        :type type: str
        """

        self._type = type

    @property
    def description(self) -> str:
        """Gets the description of this ConfigurationPropertiesValue.


        :return: The description of this ConfigurationPropertiesValue.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ConfigurationPropertiesValue.


        :param description: The description of this ConfigurationPropertiesValue.
        :type description: str
        """

        self._description = description

    @property
    def value(self) -> str:
        """Gets the value of this ConfigurationPropertiesValue.


        :return: The value of this ConfigurationPropertiesValue.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this ConfigurationPropertiesValue.


        :param value: The value of this ConfigurationPropertiesValue.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
