# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util
from swagger_server.models.metadata import Metadata
from swagger_server.models.configuration_properties_value import ConfigurationPropertiesValue


class ConfigurationProperties(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, value: List[ConfigurationPropertiesValue]=None, metadata: Metadata=None):  # noqa: E501
        """ConfigurationProperties - a model defined in Swagger

        :param type: The type of this ConfigurationProperties.  # noqa: E501
        :type type: str
        :param value: The value of this ConfigurationProperties.  # noqa: E501
        :type value: List[ConfigurationPropertiesValue]
        :param metadata: The metadata of this ConfigurationProperties.  # noqa: E501
        :type metadata: Metadata
        """
        self.swagger_types = {
            'type': str,
            'value': List[ConfigurationPropertiesValue],
            'metadata': Metadata
        }

        self.attribute_map = {
            'type': 'type',
            'value': 'value',
            'metadata': 'metadata'
        }

        self._type = type
        self._value = value
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigurationProperties':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The configuration_properties of this ConfigurationProperties.  # noqa: E501
        :rtype: ConfigurationProperties
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ConfigurationProperties.


        :return: The type of this ConfigurationProperties.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ConfigurationProperties.


        :param type: The type of this ConfigurationProperties.
        :type type: str
        """

        self._type = type

    @property
    def value(self) -> List[ConfigurationPropertiesValue]:
        """Gets the value of this ConfigurationProperties.


        :return: The value of this ConfigurationProperties.
        :rtype: List[ConfigurationPropertiesValue]
        """
        return self._value

    @value.setter
    def value(self, value: List[ConfigurationPropertiesValue]):
        """Sets the value of this ConfigurationProperties.


        :param value: The value of this ConfigurationProperties.
        :type value: List[ConfigurationPropertiesValue]
        """

        self._value = value

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this ConfigurationProperties.


        :return: The metadata of this ConfigurationProperties.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this ConfigurationProperties.


        :param metadata: The metadata of this ConfigurationProperties.
        :type metadata: Metadata
        """

        self._metadata = metadata
