# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util
from swagger_server.models.security_properties_value import SecurityPropertiesValue
from swagger_server.models.metadata import Metadata

class SecurityProperties(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, value: SecurityPropertiesValue=None, metadata: Metadata=None):  # noqa: E501
        """SecurityProperties - a model defined in Swagger

        :param type: The type of this SecurityProperties.  # noqa: E501
        :type type: str
        :param value: The value of this SecurityProperties.  # noqa: E501
        :type value: SecurityPropertiesValue
        :param metadata: The metadata of this SecurityProperties.  # noqa: E501
        :type metadata: Metadata
        """
        self.swagger_types = {
            'type': str,
            'value': SecurityPropertiesValue,
            'metadata': Metadata
        }

        self.attribute_map = {
            'type': 'type',
            'value': 'value',
            'metadata': 'metadata'
        }

        self._type = type
        self._value = value
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'SecurityProperties':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The security_properties of this SecurityProperties.  # noqa: E501
        :rtype: SecurityProperties
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this SecurityProperties.


        :return: The type of this SecurityProperties.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this SecurityProperties.


        :param type: The type of this SecurityProperties.
        :type type: str
        """

        self._type = type

    @property
    def value(self) -> SecurityPropertiesValue:
        """Gets the value of this SecurityProperties.


        :return: The value of this SecurityProperties.
        :rtype: SecurityPropertiesValue
        """
        return self._value

    @value.setter
    def value(self, value: SecurityPropertiesValue):
        """Sets the value of this SecurityProperties.


        :param value: The value of this SecurityProperties.
        :type value: SecurityPropertiesValue
        """

        self._value = value

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this SecurityProperties.


        :return: The metadata of this SecurityProperties.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this SecurityProperties.


        :param metadata: The metadata of this SecurityProperties.
        :type metadata: Metadata
        """

        self._metadata = metadata
